### ISSUE TITLE
Does it support to assign ip for multi regions?

### ISSUE THREAD

**Issue by dat-trinhtien** [binxio/ec2-elastic-ip-manager#6]
Hello, 
I have ASG in 3 regions, and I want to apply ec2-elastic-ip-manager for them.
so, we need to deploy ec2-elastic-ip-manager on each region or we can just deploy once and use for all?
Thank you,
Dat.

**Comment by mvanholsteijn** [comment]
Like the EIPs and ASGs the eip manager is a regional resource.
